AWSTemplateFormatVersion: 2010-09-09
Description: pipeline codebuild
Parameters:
  GitRepo:
    Type: String
  GitBranch:
    Type: String
  GitSecret:
    Type: String
  GitToken:
    Type: String
  GitOwner:
    Type: String

Resources:
  # Role to build build enviornment infrustructure
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-BuildRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
              - codebuild.amazonaws.com
          Action:
            - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-BuildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:*
                  - iam:*
                  - logs:*
                Resource: "*"

  BuildPipeline:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-BuildPipeline
      Description: Test and build pipeline
      ServiceRole: !GetAtt BuildRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: golang
        #Image: aws/codebuild/golang:1.11
      Source:
        Type: CODEPIPELINE
        BuildSpec: ci/buildspec.yml